### ISSUE TITLE
Error - Not importing view

### ISSUE THREAD

**Issue by princego** [materialsproject/crystaltoolkit#112]
I tried this command in jupyter notebook

**from crystal_toolkit import view**
ImportError: cannot import name 'view' from 'crystal_toolkit' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/crystal_toolkit/__init__.py)

I have installed Python 3.8.4 and crystal-toolkit 2020.6.4 installed using pip

**Comment by mkhorton** [comment]
Thanks @princego, the new instructions are here: https://github.com/materialsproject/crystaltoolkit/blob/master/docs_rst/jupyter.rst

The notice on the homepage:

> Crystal Toolkit is not ready for the public yet! Please wait for a release announcement soon, thank you :-)

is still valid though. There are known bugs, but by all means give it a go!
