### ISSUE TITLE
Cannot display 3D model

### ISSUE THREAD

**Issue by ShiQiaoL** [materialsproject/crystaltoolkit#219]
When I use Crystal Toolkit in jupyter lab 3.x, there is no error message, but the 3D results cannot be displayed
![image](https://user-images.githubusercontent.com/42061037/141080573-32212fb0-3575-4eeb-a274-71e4c2c72e63.png)

**Comment by mkhorton** [comment]
Hi @ShiQiaoL, can you provide more information? What web browser are you using? If you `print(LiFePO4)` what do you see?

**Comment by mkhorton** [comment]
Also, you can try `pip install --upgrade crystaltoolkit-extension`

**Comment by mkhorton** [comment]
Another user has reported a similar issue, I will investigate. It's possible the latest v0.5.0 version of `crystaltoolkit-extension` is bad and will need to be pulled.

**Comment by ShiQiaoL** [comment]
> Hi @ShiQiaoL, can you provide more information? What web browser are you using? If you `print(LiFePO4)` what do you see?

Thank you for your help
The web browser is Microsoft Edge.
![image](https://user-images.githubusercontent.com/42061037/141255671-5a71bc2e-6ac8-41f7-be14-4f067d438728.png)
 When I `print(LiFePO4)`, I can see the crystal information；
![image](https://user-images.githubusercontent.com/42061037/141255943-336447d5-aab0-474b-bba3-e8e02e666390.png)

In addition, I have Successfully installed crystaltoolkit-extension-0.5.0
![image](https://user-images.githubusercontent.com/42061037/141256282-915ba8c3-922e-4f8e-a18b-a88542b9f656.png)

however, the issue still exists。

**Comment by mkhorton** [comment]
This should now work with `crystaltoolkit-extension` 0.6.0, thanks for reporting the issue.
