### ISSUE TITLE
pip install fails on arm64 (M1 Mac)

### ISSUE THREAD

**Issue by janosh** [materialsproject/crystaltoolkit#228]
`pip install crystal-toolkit` fails with:

> OSError: Could not find library geos_c or load any of its variants ['/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib', '/usr/local/lib/libgeos_c.dylib', '/opt/homebrew/lib/libgeos_c.dylib']

<details>
<summary>Full pip install logs</summary>

```sh
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Failed `CDLL(/Library/Frameworks/GEOS.framework/Versions/Current/GEOS)`
      Failed `CDLL(/opt/local/lib/libgeos_c.dylib)`
      Failed `CDLL(/usr/local/lib/libgeos_c.dylib)`
      Failed `CDLL(/opt/homebrew/lib/libgeos_c.dylib)`
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/5m/sb0wx83j0m36xk_zswkfnffh0000gn/T/pip-install-stxi_jkw/shapely_52a19b9f150646e4bcd48901f3c4c7e7/setup.py", line 74, in <module>
          from shapely._buildcfg import geos_version_string, geos_version, \
        File "/private/var/folders/5m/sb0wx83j0m36xk_zswkfnffh0000gn/T/pip-install-stxi_jkw/shapely_52a19b9f150646e4bcd48901f3c4c7e7/shapely/_buildcfg.py", line 189, in <module>
          lgeos = load_dll('geos_c', fallbacks=alt_paths)
        File "/private/var/folders/5m/sb0wx83j0m36xk_zswkfnffh0000gn/T/pip-install-stxi_jkw/shapely_52a19b9f150646e4bcd48901f3c4c7e7/shapely/_buildcfg.py", line 159, in load_dll
          raise OSError(
      OSError: Could not find library geos_c or load any of its variants ['/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib', '/usr/local/lib/libgeos_c.dylib', '/opt/homebrew/lib/libgeos_c.dylib']
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
</details>

Worked fine installing on a Linux cluster so seems M1 specific.

**Comment by janosh** [comment]
Ah, looks like there's a [well known issue with `llvmlite` on M1](https://github.com/numba/llvmlite/issues/693) and `numba` is [working on fixing it](https://github.com/numba/llvmlite/issues/693#issuecomment-1026839237).

**Comment by janosh** [comment]
FWIW, this finally succeeded:

```sh
brew install llvm@11
LLVM_CONFIG="/opt/homebrew/Cellar/llvm@11/11.1.0_4/bin/llvm-config" pip install llvmlite

brew install hdf5
export HDF5_DIR=/opt/homebrew/Cellar/hdf5/1.12.1
pip install --no-binary=h5py h5py

pip install crystal-toolkit
```

**Comment by mkhorton** [comment]
Thanks for the report and update on this issue.

It's possible this dependency can be relaxed in future versions too, but hopefully with arm64 support getting gradually better throughout the ecosystem this won't be necessary.

**Comment by janosh** [comment]
The `numba` dependence still causes installation problems (at least on M1 Macs).

Quoting @mkhorton: `numba` is used by `dscribe`, which is used by both `matminer` (an `emmet-core` dep) and also the `local_env` feature in `crystal toolkit`. it could certainly be made optional. It's a headache because `numba` doesn't support the latest `numpy`, and `pymatgen` is often tracking a later `numpy` version (because it requires binary compatibility with the compiled extensions).

Decided to go with optional `numba` dependence. Will just need a corresponding change here to check for an ImportError:

https://github.com/materialsproject/crystaltoolkit/blob/ae03e10290dfc9a5060ae2691044dfdffc0f6215/crystal_toolkit/components/localenv.py#L11-L12
