### ISSUE TITLE
Error when rendering disordered sites in jupyter

### ISSUE THREAD

**Issue by lbluque** [materialsproject/crystaltoolkit#234]
I am trying to visualize a disordered structure in a jupyter notebook.

But I get the following error:
```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/opt/miniconda3/envs/matx_dev/lib/python3.9/site-packages/IPython/core/formatters.py in __call__(self, obj, include, exclude)
    968 
    969             if method is not None:
--> 970                 return method(include=include, exclude=exclude)
    971             return None
    972         else:

~/opt/miniconda3/envs/matx_dev/lib/python3.9/site-packages/crystal_toolkit/__init__.py in _repr_mimebundle_(self, include, exclude)
     56     if hasattr(self, "get_scene"):
     57         return {
---> 58             "application/vnd.mp.ctk+json": self.get_scene().to_json(),
     59             "text/plain": help_text_ct + self.__repr__(),
     60         }

~/opt/miniconda3/envs/matx_dev/lib/python3.9/site-packages/crystal_toolkit/renderables/structure.py in get_structure_scene(self, origin, legend, draw_image_atoms)
     97             )
     98 
---> 99         site_scene = site.get_scene(legend=legend,)
    100         for scene in site_scene.contents:
    101             primitives[scene.name] += scene.contents

~/opt/miniconda3/envs/matx_dev/lib/python3.9/site-packages/crystal_toolkit/renderables/site.py in get_site_scene(self, connected_sites, connected_sites_not_drawn, hide_incomplete_edges, incomplete_edge_length_scale, connected_sites_colors, connected_sites_not_drawn_colors, origin, draw_polyhedra, explicitly_calculate_polyhedra_hull, bond_radius, draw_magmoms, magmom_scale, legend)
    143             positions=[position],
    144             color="#ffffff",
--> 145             radius=self.properties["display_radius"][0],
    146             phiStart=phiEnd,
    147             phiEnd=np.pi * 2,

KeyError: 'display_radius'
```

The error is in this line: https://github.com/materialsproject/crystaltoolkit/blob/48050356cbe8b07fa4123bfb964705cb26991c4a/crystal_toolkit/renderables/site.py#L145

Setting a `"display_radius"` property for all sites also does not work, since prior to this it expects a float, but in the line above it assumes it is subscriptable.

I think that line may be some form of typo, and what was really meant was to use the radius of one of the already created `Sphere` objects. Otherwise I am not so sure, which is why I haven't made a PR with a fix for this.

**Comment by mkhorton** [comment]
Hi @lbluque, thanks for reporting.

I think this may be an un-tested code block: this purpose of this block is if you have a disordered structure where the site occupancies do not sum to 1, and so you have a little slice "left over", and it's aesthetically useful to fill this in with something otherwise you will see the inside of the sphere. The radius here, then, is not really meaningful.

I think setting:

```
radius=max_radius,
```

on L145 would fix it.

**Comment by mkhorton** [comment]
If you can confirm this fix works, I can commit it + re-release.

**Comment by lbluque** [comment]
works like a charm!

thanks @mkhorton
