### ISSUE TITLE
setting crystal-toolkit display options in jupyter-lab

### ISSUE THREAD

**Issue by ErnstRob** [materialsproject/crystaltoolkit#246]
How to adjust display options for displaying pymatgen structures with the help of the crystal-toolkit, for instance show bonds on/off.
Is it on crystal-toolkit side or pymatgen side?
Where to look in the API documentation for things like this?

**Comment by mkhorton** [comment]
Hi @ErnstRob,

Thanks for the question. The options are in the `Structure.get_scene()` or `StructureGraph.get_scene()` methods, which you can return in a Jupyter cell. There needs to be a documentation page on this, my apologies this has not yet been added.

See here for an example of the options available: https://github.com/materialsproject/crystaltoolkit/blob/50debdea383f2fdaafda44e95db12a4f81851a16/crystal_toolkit/renderables/structuregraph.py#L83-L96

Please feel free to ask any follow-up questions here!
