### ISSUE TITLE
SpectrumComponent

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/crystaltoolkit#3]
A UI component for` pymatgen.core.spectrum.Spectrum`

**Comment by mkhorton** [comment]
@mattmcdermott 

As discussed earlier, with the new project layout, an `XRayDiffractionComponent` could in `crystal_tookit/components/xrd.py`, and it'd look something like:

```
import dash
import dash_core_components as dcc
import dash_html_components as html

from crystal_toolkit.helpers.layouts import *  # layout helpers like `Columns` etc. (most subclass html.Div)

from crystal_toolkit.components.core import MPComponent

class XRayDiffractionComponent(MPComponent):

    @property
    def all_layouts():
        returns {'graph': ..., 'controls': ..., etc.}

    @property
    def standard_layout():
        returns html.Div([self.all_layouts['graph'], self.all_layouts['controls'])

    def _generate_callbacks(self, app, cache):

        @app.callback(...)
        def callback_here():
            ...
```

To use, you can test in a sample `usage.py`, where it would look something like:

```
import crystal_toolkit as ct

...define app...

ct.register_app(app)
ct.register_cache(cache)

xrd_component = XRayDiffractionComponent(my_struct)

app.layout = xrd_component.standard_layout

```

Finally, to name ids, use MPComponent's `id` method, so `html.Div(id=self.id("my-div"))`. This ensures that multiple instances of the same MPComponent can be used (eg displaying multiple XRD spectra on the same page).

**Comment by mkhorton** [comment]
Also, there may still be changes necessary for the base class / this may not be suitable for your needs as-is and you should feel welcome to modify it, but this should at least work as a starting point.

**Comment by mattmcdermott** [comment]
Closing with addition of XRD and XAS components.
