### ISSUE TITLE
StructureMoleculeComponent and Mobile Devices

### ISSUE THREAD

**Issue by lantunes** [materialsproject/crystaltoolkit#346]
The `StructureMoleculeComponent` renders on mobile devices, but I'm unable to rotate the structure in the viewer. I can only zoom in and out on the structure. The viewer's buttons (e.g. settings, export) work normally. I've encountered this on a Pixel 4a and iPhone 8, using a Chrome browser.

**Comment by janosh** [comment]
You have to swipe across with 2 fingers to rotate. I just tried it out on iPhone 14 and it's admittedly quite hard to control but that seems to be the intended behavior.

**Comment by janosh** [comment]
Closing as closed. Feel free to ping back if you think the current behavior needs changing.
