### ISSUE TITLE
species_and_occu -> site.species ?

### ISSUE THREAD

**Issue by dwinston** [materialsproject/crystaltoolkit#50]
I get a slew of deprecation warnings from pymatgen for the structure module:
```
../crystal_toolkit/components/structure.py:1304: DeprecationWarning:

species_and_occu is deprecated
Use site.species instead. This will be deprecated with effect from pymatgen 2020.
```
I don't know enough about this to start a PR.

**Comment by mkhorton** [comment]
Thanks @dwinston , SP recently made a bunch of changes to Structure partly in response to some feedback we got. I think a refactor to replace all `species_and_occu` with `species` will be sufficient (both properties run the exact same code).

**Comment by dwinston** [comment]
I see. Yes, [this appears to be the case](https://github.com/materialsproject/pymatgen/blob/1bbfaf1eec0b4c5cc9db8a26a18611192f129b32/pymatgen/core/sites.py#L166-L173).

**Comment by mkhorton** [comment]
Might re-visit this .. the important thing is that you get a Composition you can iterate over, I haven't actually examined the underlying change
